-- ============================================================
-- ENROLLMENTS TABLE
-- Join table linking STUDENTS <-> CLASS <-> COURSES
-- Synchronizes STUDENTS.CLASS_ID / STUDENTS.COURSE_ID on change
-- ============================================================
USE NOKORTECH_LMS_DB;

DROP TABLE IF EXISTS ENROLLMENTS;

CREATE TABLE ENROLLMENTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(30) NOT NULL UNIQUE,
    STUDENT_ID INT NOT NULL,
    CLASS_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    ENROLLED_DATE DATE NOT NULL,
    STATUS ENUM('Enrolled', 'Completed', 'Dropped') NOT NULL DEFAULT 'Enrolled',
    NOTE TEXT NULL,
    CREATED_BY INT NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY INT NULL,
    UPDATED_DATE TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,

    -- Prevent the same student being enrolled twice into the same class/course
    UNIQUE KEY UNIQ_STUDENT_CLASS_COURSE (STUDENT_ID, CLASS_ID, COURSE_ID),

    -- Foreign Key Constraints
    CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ENROLL_CLASS FOREIGN KEY (CLASS_ID) REFERENCES CLASS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ENROLL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ENROLL_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID) ON DELETE SET NULL
);